name: "dependent jobs"

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        run: echo "first job - step1"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: "step2"
        run: echo "second job - step2"
